
################### VER 3 of Docker ########################
FROM rabbitmq:3.10-management-alpine


# Define environment variables.
ENV RABBITMQ_USER myuser
ENV RABBITMQ_PASSWORD mypassword
ENV RABBITMQ_VHOST myvhost
ENV RABBITMQ_PID_FILE /var/lib/rabbitmq/mnesia/rabbitmq
# ENV RABBITMQ_USER = .env/RABBITMQ_USER
# ENV RABBITMQ_PASSWORD = .env/RABBITMQ_PASSWORD
# ENV RABBITMQ_VHOST = .env/RABBITMQ_VHOST
# ENV RABBITMQ_PID_FILE = .env/RABBITMQ_PID_FILEs

ADD ./scripts/init.sh /init.sh
RUN chmod +x /init.sh
EXPOSE 5672

# Define default command
CMD ["/init.sh"]
